# -*- coding: utf-8 -*-
"""pandas_basics

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rTyOwgRnLodqGstBKH-ulb_HSjhFzl6V
"""

# pandas Series -> A Pandas Series is like a column in a table.

arr = [5,7,9,11]

ser = pd.Series(arr)
print(ser[1])

ser2 = pd.Series(arr, index = ["x","y","z","a"])
print(ser2)

# using dictionaries as data for series

todos = {
    'day1': "Legday",
    'day2': "Chest",
    'day3': "Back",
    'day4': "Shoulders",
    'day5': "Arms"
}

#  display only those data which we want by specifying the index
#  Suppose we want only leg,arms & shoulders..

mydata2 = pd.Series(todos, index = ['day1','day4','day5'])
print(mydata2)

import pandas as pd

# Data sets in Pandas are usually multi-dimensional tables, called DataFrames.
# Series is like a column, a DataFrame is the whole table

mydata = {
    'cars' : ["Mercedes", "BMW", "Skoda"],
    'rating': [8,9,6]
}

df = pd.DataFrame(mydata)
print(df)

# To get a row or specified rows from the dataFrame
#  use loc ->ie locate row

# when we use directly loc it returns a pandas Series
print(df.loc[0])
print("------------------------------")

# when we use [] it returns a dataframe
print(df.loc[[0,2]])

# With the index argument, you can name your own indexes.
todos2 = {
    'workout': ["Legs", "Arms", "Chest", "Shoulders"],
    'time': ["1hr", "2hr", "1.5hr", "1hr"]
}

df2 = pd.DataFrame(todos2, index = ["Mon","Wed","Thu", "Sat"])
# print(df2)

print(df2.loc[['Mon','Sat']])